/*
 * STEPPER_prg.c
 *
 *  Created on: Jul 22, 2025
 *      Author: anaal
 */


#include "STEPPER_int.h"
#include "STEPPER_cfg.h"

void HSTEPPER_vInit(){
	MDIO_vSetPinDirection(STEPPER_CONTROL_PORT, B, DIO_PIN_DIRECTION_OUTPUT);
	MDIO_vSetPinDirection(STEPPER_CONTROL_PORT, P, DIO_PIN_DIRECTION_OUTPUT);
	MDIO_vSetPinDirection(STEPPER_CONTROL_PORT, Y, DIO_PIN_DIRECTION_OUTPUT);
	MDIO_vSetPinDirection(STEPPER_CONTROL_PORT, O, DIO_PIN_DIRECTION_OUTPUT);
}

void HSTEPPER_vMove(){
	MDIO_vSetPinValue(STEPPER_CONTROL_PORT, B, DIO_PIN_HIGH);
	MDIO_vSetPinValue(STEPPER_CONTROL_PORT, P, DIO_PIN_LOW);
	MDIO_vSetPinValue(STEPPER_CONTROL_PORT, Y, DIO_PIN_LOW);
	MDIO_vSetPinValue(STEPPER_CONTROL_PORT, O, DIO_PIN_LOW);
	_delay_ms(10);
	MDIO_vSetPinValue(STEPPER_CONTROL_PORT, B, DIO_PIN_LOW);
	MDIO_vSetPinValue(STEPPER_CONTROL_PORT, P, DIO_PIN_HIGH);
	MDIO_vSetPinValue(STEPPER_CONTROL_PORT, Y, DIO_PIN_LOW);
	MDIO_vSetPinValue(STEPPER_CONTROL_PORT, O, DIO_PIN_LOW);
	_delay_ms(10);
	MDIO_vSetPinValue(STEPPER_CONTROL_PORT, B, DIO_PIN_LOW);
	MDIO_vSetPinValue(STEPPER_CONTROL_PORT, P, DIO_PIN_LOW);
	MDIO_vSetPinValue(STEPPER_CONTROL_PORT, Y, DIO_PIN_HIGH);
	MDIO_vSetPinValue(STEPPER_CONTROL_PORT, O, DIO_PIN_LOW);
	_delay_ms(10);
	MDIO_vSetPinValue(STEPPER_CONTROL_PORT, B, DIO_PIN_LOW);
	MDIO_vSetPinValue(STEPPER_CONTROL_PORT, P, DIO_PIN_LOW);
	MDIO_vSetPinValue(STEPPER_CONTROL_PORT, Y, DIO_PIN_LOW);
	MDIO_vSetPinValue(STEPPER_CONTROL_PORT, O, DIO_PIN_HIGH);
	_delay_ms(10);
}
void HSTEPPER_vMoveSpecificAngle(u16 A_u8Angle){

	u16 Local_u16Steps = (u16)(A_u8Angle / STEPPER_STRIDE_ANGLE);

	for(int i = 0 ; i<(Local_u16Steps/4) ; i++){
		MDIO_vSetPinValue(STEPPER_CONTROL_PORT, B, DIO_PIN_HIGH);
		MDIO_vSetPinValue(STEPPER_CONTROL_PORT, P, DIO_PIN_LOW);
		MDIO_vSetPinValue(STEPPER_CONTROL_PORT, Y, DIO_PIN_LOW);
		MDIO_vSetPinValue(STEPPER_CONTROL_PORT, O, DIO_PIN_LOW);
		_delay_ms(10);
		MDIO_vSetPinValue(STEPPER_CONTROL_PORT, B, DIO_PIN_LOW);
		MDIO_vSetPinValue(STEPPER_CONTROL_PORT, P, DIO_PIN_HIGH);
		MDIO_vSetPinValue(STEPPER_CONTROL_PORT, Y, DIO_PIN_LOW);
		MDIO_vSetPinValue(STEPPER_CONTROL_PORT, O, DIO_PIN_LOW);
		_delay_ms(10);
		MDIO_vSetPinValue(STEPPER_CONTROL_PORT, B, DIO_PIN_LOW);
		MDIO_vSetPinValue(STEPPER_CONTROL_PORT, P, DIO_PIN_LOW);
		MDIO_vSetPinValue(STEPPER_CONTROL_PORT, Y, DIO_PIN_HIGH);
		MDIO_vSetPinValue(STEPPER_CONTROL_PORT, O, DIO_PIN_LOW);
		_delay_ms(10);
		MDIO_vSetPinValue(STEPPER_CONTROL_PORT, B, DIO_PIN_LOW);
		MDIO_vSetPinValue(STEPPER_CONTROL_PORT, P, DIO_PIN_LOW);
		MDIO_vSetPinValue(STEPPER_CONTROL_PORT, Y, DIO_PIN_LOW);
		MDIO_vSetPinValue(STEPPER_CONTROL_PORT, O, DIO_PIN_HIGH);
		_delay_ms(10);
		 MDIO_vSetPinValue(STEPPER_CONTROL_PORT, O, DIO_PIN_LOW);
	}
}
