/*
 * EXT_INT_cfg.h
 *
 *  Created on: Jul 23, 2025
 *      Author: anaal
 */

#ifndef MCAL_EXT_INTERRUPT_EXT_INT_CFG_H_
#define MCAL_EXT_INTERRUPT_EXT_INT_CFG_H_

#define EXT_INT_ENABLE		1
#define EXT_INT_DISABLE		0


#define	EXT_INT0_CFG	EXT_INT_DISABLE
#define	EXT_INT1_CFG	EXT_INT_ENABLE
#define	EXT_INT2_CFG	EXT_INT_DISABLE

#define EXT_INT_SENSTIVITY_CFG				EXT_INT_LOW_LEVEL_SENSTIVITY_CFG

#define	EXT_INT_LOW_LEVEL_SENSTIVITY_CFG				0
#define	EXT_INT_ANY_LOGIC_CHANGE_SENSTIVITY_CFG			1
#define	EXT_INT_FALLING_EDGE_SENSTIVITY_CFG				2
#define	EXT_INT_RISING_EDGE_SENSTIVITY_CFG				3







#endif /* MCAL_EXT_INTERRUPT_EXT_INT_CFG_H_ */
